#!/usr/bin/env python3
# isort: skip_file
"""Deploy script for anemoi_test suite.
This has been generated by the wellies-quickstart and the following versions:
{
    "ecflow": "5.13.8",
    "pyflow": "3.5.1",
    "tracksuite": "0.4.2",
    "wellies": "1.2.0"
}

for options, see:
./deploy.py --help
"""
import logging
from anemoi_test.config import Config
from anemoi_test.nodes import MainSuite

import pyflow as pf
import wellies as wl
from wellies.show_versions import show_versions

logger = logging.getLogger("anemoi_test")


if __name__ == "__main__":

    # Create parser and parse arguments
    parser = wl.get_parser()
    args = parser.parse_args()

    # Set log level from args
    logging.basicConfig(level=args.log_level, format="[%(levelname)s]%(name)s: %(message)s")
    logger.debug(f"deploying with versions: \n{show_versions(as_dict=True)}")

    # Create config object and suite
    logger.debug("Creating Config instance")
    config = Config(args)
    ecflow_server = config.ecflow_server

    logger.debug("Initialising Suite instance")
    # Empty top level suite to allow group/user structure on ecflow server
    with pf.Suite(config.group, files=ecflow_server.deploy_dir) as suite:
        MainSuite(
            config,
            name=config.name,
            host=config.host,
            variables=config.suite_variables,
            limits=config.limits,
            labels=config.labels,
        )

    # Deploy suite scripts and definition file
    logger.info(f"Deploying suite to {ecflow_server.hostname}:{ecflow_server.deploy_dir}")
    wl.deploy_suite(
        suite,
        name=config.name,
        hostname=ecflow_server.hostname,
        user=ecflow_server.user,
        deploy_dir=ecflow_server.deploy_dir,
        backup_deploy=config.backup_deploy,
        build_dir=args.build_dir,
        no_prompt=args.y,
        no_deploy=args.no_deploy,
        message=args.message,
    )
